config/routes.rb
Rails.application.routes.draw do

  root "pages#posts"
  
  get "search" => "pages#search"
  get "manage" => "pages#manage"
  get "profile" => "pages#profile"

  resources :attachments, only: [:destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope module: "users" do
    resources :posts do
      collection do
        get "remind_for_draft"
      end
      member do
        get "upload_photo"
        post "update_attachment"
        get "preview"
        post "publish"
        post "unpublish"
      end
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  enum state: { draft: 0, hidden: 1, publish: 2 }
  enum availability: { available: 0, taken: 1 }
  enum post_type: { renting: 0, replacement: 1, matching: 2 }

  include Imageable
  include Tokenable

  default_scope { order(updated_at: :desc) }

  validates :price, :post_type, :description, :city, :address, presence: true

  belongs_to :author, class_name: "User", foreign_key: :author_id, counter_cache: true

  # 驗證 enum 時需使用字串，不可使用整數，否則會被擋下
  def self.valid_attribute?(attr, value)
    mock = self.new(attr => value)
    unless mock.valid?
      return !mock.errors.has_key?(attr)
    end
    true
  end

  def self.valid_attributes?(params)
    params.each do |k,v|
      return false unless self.valid_attribute?(k,v)
    end
    true
  end

  def can_publish?
    self.valid? && self.attachments_count > 0
  end

  def i18n_short_type # for _post 用
    I18n.t("post_type.short.#{self.post_type}")
  end

  def self.i18n_types # for select 用
    I18n.t("post_type.long")
  end

  def full_address
    if self.city.blank? && self.address.blank?
      "尚未輸入地址"
    else
      "#{self.city}#{self.address}"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :trackable, :omniauthable, :database_authenticatable

  has_many :posts, dependent: :destroy, foreign_key: :author_id

  def fb
    "https://www.facebook.com/#{uid}"
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.image = auth.info.image
      user.email = auth.info.email
    end
  end

  def has_draft?
    return self.posts.draft.present?
  end
end

app/controllers/deprecated/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to upload_photo_post_path(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def upload_photo
    @post = Post.find_by_id(params[:id])
  end

  def update_attachment
    @post = Post.find_by_id(params[:id])
    #name  = params[:file]
    #style = params[:attachment_style]
    #image = params[:user][name]
    if params[:file]
      params[:file].each { |picture| @post.attachments.create(:image => picture) }
    end
    #render(json: current_user.to_fileupload(name, style), content_type: request.format)
    redirect_to upload_photo_post_path
  end

  def preview
    @post = Post.find_by_id(params[:post_id])
  end

  def publish
    @post = Post.find_by_id(params[:post_id])
    @post.publish!
    redirect_to posts_path, notice: "成功刊登！"
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to upload_photo_post_path(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:address, :price, :description, :post_type, :user_id, :status)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    #@posts = Post.all
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to upload_photo_post_path(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def upload_photo
    @post = Post.find_by_id(params[:id])
  end

  def update_attachment
    @post = Post.find_by_id(params[:id])
    #name  = params[:file]
    #style = params[:attachment_style]
    #image = params[:user][name]
    if params[:file]
      params[:file].each { |picture| @post.attachments.create(:image => picture) }
    end
    #render(json: current_user.to_fileupload(name, style), content_type: request.format)
    redirect_to upload_photo_post_path
  end

  def preview
    @post = Post.find_by_id(params[:post_id])
  end

  def publish
    @post = Post.find_by_id(params[:post_id])
    @post.publish!
    redirect_to posts_path, notice: "成功刊登！"
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to upload_photo_post_path(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:address, :price, :description, :post_type, :user_id, :status)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_order_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upload_photo, :update_attachment, :preview, :publish, :unpublish]

  def index
    @posts = current_user.posts.all
  end

  # def show
  # end

  def remind_for_draft # 作為到新刊登之前的緩衝，避免使用者持續重新刊登
    if current_user.has_draft?
      redirect_to posts_path
    else
      redirect_to new_post_path
    end
  end

  # GET /posts/new
  def new
    current_user.posts.new.save(validate: false) unless current_user.has_draft?
    @post = current_user.posts.draft.first
  end

  # GET /posts/1/edit
  def edit
  end

  def update
    respond_to do |format|
      # byebug
      # 注意此處不可用 @post.update_columns
      # 因為 update_columns 不會將 enum 從字串轉為整數
      # 但驗證時又需要驗證字串，所以改用 assign + save
      if Post.valid_attributes?(post_params) && (@post.attributes = post_params) && @post.save(validate:false)
        format.html { 
          if @post.valid?
            redirect_to upload_photo_post_path(@post)
          else
            redirect_to edit_post_path(@post)
          end
        }
        format.json { render :show, status: :ok, location: @post }
      end
    end
  end

  # def create
  #   @post = current_user.posts.new(post_params)

  #   respond_to do |format|
  #     if Post.valid_attributes?(post_params) && @post.save(validate: false)
  #       if @post.valid?
  #         format.html { redirect_to upload_photo_post_path(@post), notice: 'Post was successfully created.' }
  #         format.json { render :show, status: :created, location: @post }
  #       else
  #         format.html { redirect_to edit_post_path(@post) }
  #         # format.html { render :new }
  #         # format.json { render json: @post.errors, status: :unprocessable_entity }
  #       end
  #     end
  #   end
  # end

  def upload_photo
    redirect_to edit_post_path(@post) unless @post.valid?
  end

  def update_attachment
    respond_to do |format|
      if params[:file]
        params[:file].each { |picture| @post.attachments.create(:image => picture) }
      end
      format.html { redirect_to upload_photo_post_path }
      format.json { render :upload_photo, status: :created, location: @post }
    end
  end

  def preview
    if @post.publish?
      redirect_to posts_path
    elsif @post.draft?
      if @post.can_publish? # 檢查各屬性及圖片數量大於 1
        @post.hidden!
      elsif @post.attachments_count.zero?
        redirect_to upload_photo_post_path(@post)
      else
        redirect_to edit_post_path(@post)
      end
    end
  end

  def publish
    if @post.can_publish?
      @post.publish!
      flash[:success] = "發佈成功。"
      redirect_to root_path
    else
      redirect_to :back
    end
  end

  def unpublish
    @post.hidden!
    redirect_to :back
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_user.posts.find_by_id(params[:id])
      redirect_to profile_path unless @post.present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:city, :address, :price, :description, :state, :availability, :post_type, :author_id, :token, :attachments_count)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def cities
    if I18n.locale == :'en'
      {"Keelung": "基隆市", "Taipei": "台北市", "Yilan": "宜蘭縣", "Hsinchu": "新竹市", "Hsinchu County": "新竹縣", "Taoyuan": "桃園市", "Miaoli": "苗栗縣", "Taichung": "台中市", "Changhua": "彰化縣", "Nantou": "南投縣", "Chiayi": "嘉義市", "Chiayi County": "嘉義縣", "Yunlin": "雲林縣", "Tainan": "台南市", "Kaohsiung": "高雄市", "Pingtung": "屏東縣", "Taitung": "台東縣", "Hualien": "花蓮縣", "Kinmen County": "金門縣", "Lienchiang County": "連江縣", "Penghu County": "澎湖縣"}
    else
      ["基隆市","台北市","宜蘭縣","新竹市","新竹縣","桃園市","苗栗縣","台中市","彰化縣","南投縣","嘉義市","嘉義縣","雲林縣","台南市","高雄市","屏東縣","台東縣","花蓮縣","金門縣","連江縣","澎湖縣"]
    end
  end

  def render_main_btn(text = nil, path = "#", html_options = {class:nil, id:nil})
    default_class = "ui button yellow main-bottom-btn"
    html_options[:class] = "#{default_class} #{html_options[:class]}"
    link_to path, html_options do
      text
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/posts/_form.html.erb
<%= form_for @post, html: { class: 'ui form' } do |f| %>
  <% if false#@post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="column">
    <div class="field">
      <div class="ui grid">
        <div class="eight wide column">
          <div class="field">
            <%= f.label :price, "NT$" %>
            <%= f.text_field :price %>
          </div>
        </div>
        <div class="eight wide column">
          <div class="field">
            <%= f.label :post_type, "刊登類型" %>
            <% if true#browser.platform.ios? %>
              <div class="ios_dropdown_with_icon">
                <%= f.collection_select :post_type, Post.i18n_types, :first, :last, {}, class: "ui fluid dropdown default" %>
                <i class="dropdown icon"></i>
              </div>
            <% else %>
              <%= f.collection_select :post_type, Post.post_types, :last, :first, {include_blank: true}, class: "ui fluid selection dropdown" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="field">
      <%= f.label :description, '描述' %>
      <%= f.text_area :description, rows: '5' %>
    </div>
    <div class="field">
      <div class="ui grid">
        <div class="six wide column">
          <div class="field">
            <%= f.label :city, "城市" %>
            <% if true#browser.platform.ios? %>
              <div class="ios_dropdown_with_icon">
                <%= f.collection_select :city, I18n.t('cities'), :last, :last, {default: "台北市"}, class: "ui dropdown default" %>
                <i class="dropdown icon"></i>
              </div>
            <% else %>
              <%= f.collection_select :city, I18n.t('cities'), :first, :last, {include_blank: "台北市"}, class: "ui compact search selection dropdown" %>  
            <% end %>
          </div>
        </div>
        <div class="ten wide column">
          <div class="field">
            <%= f.label :address, "地址" %>
            <%= f.text_field :address %>
          </div>
        </div>
      </div>
    </div>
  </div>

      <!-- <div class="ui embed" data-url="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3614.3228017997767!2d121.53782731486504!3d25.0570459839616!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMjXCsDAzJzI1LjQiTiAxMjHCsDMyJzI0LjEiRQ!5e0!3m2!1szh-TW!2stw!4v1457601553949"></div> -->
  <div class="center">
    <%= link_to "清除重填", "#", id:"reset-btn", class:"ui mini button basic black" %>
    <%= f.submit "下一步", class: "ui button green submit-buttom" %>
  </div>
  
<% end %>




<%= content_for :custom_js do %>
  <script type="text/javascript">
    $("form textarea, form input, form select").change(function(){
      $.ajax({
          type      : 'POST',
          data      : { "post": {
            "price": $('input[name="post[price]"]').val(),
            "description": $('textarea[name="post[description]"]').val(),
            "post_type": $('select[name="post[post_type]"]').val(),
            "city": $('select[name="post[city]"]').val(),
            "address": $('input[name="post[address]"]').val()
          }, _method: 'put' }, // our data object
          url       : $('form').attr('action'), // the url where we want to POST
          dataType  : 'json', // what type of data do we expect back from the server
          encode    : true
        })
            // using the done promise callback
            .done(function(data) {

              // log data to the console so we can see
              console.log(data);

              // here we will handle errors and validation messages
            });
    })
    $("#reset-btn").click(function(){
      $('form').form('clear')
      //$('form').form('set value', 'post[post_type]', 'renting')
      //('form').form('set value', 'post[city]', 'Taipei')
      $('form div.default.text').removeClass('default')
    })
    $(document).ready(function() {
      $('.ui.form')
        .form({
          on: 'submit',
          fields: {
            post_price     : ['empty','integer'],
            post_post_type   : 'empty',
            post_city   : 'empty',
            post_description : 'empty',
            post_address : 'empty'
          }
        })
      ;

      // $('a.item').click(function(e){
      //   if ($('.ui.form textarea').val().length > 0) {
      //     console.log("123")
      //     e.preventDefault()
      //     $('.ui.main.container').append('<div class="ui icon message"><i class="inbox icon"></i><div class="content"><div class="header">要放棄編輯？</div><p>Get the best news in your e-mail every day.</p></div></div>')
      //   }  
      // })
    })
  </script>
<% end %>

app/views/users/posts/edit.html.erb
<h2 class="ui center aligned icon header">
  <!-- <i class="circular home icon"></i> -->
  需要幫助嗎？ <%= link_to '聯絡 Zuker', ENV["zuker_community_shorturl"], target: "_blank" %>
</h2>
<%= render 'form' %>

app/views/users/posts/index.html.erb
<%= content_for :outside do %>
  <%= render "users/partials/remind_for_draft" if current_user.has_draft? %>
<% end %>

<div id="home">
  <div class="ui grid">
    <% @posts.each do |post| %>
      <div class="row">
        <div class="column no_horizontal_paddings">
          <%= render "posts/post", post: post %>
        </div>
      </div>
    <% end %>
  </div>

  <%= stylesheet_link_tag 'owl-carousel/owl.carousel.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'owl-carousel/owl.theme.css', media: 'all', 'data-turbolinks-track' => true %>

  <%= content_for :custom_js do %>
    <%= javascript_include_tag 'owl-carousel/owl.carousel.js', 'data-turbolinks-track' => true %>
    <script type="text/javascript">
      $(".owl-carousel").owlCarousel({
        //autoPlay: 3000, //Set AutoPlay to 3 seconds
        //singleItem: true,
        items: 1,
        itemsDesktop: false,
        itemsDesktopSmall: false,
        itemsTablet: false,
        itemsTabletSmall: false,
        lazyLoad : true,
        navigation : false,
        pagination : false,
      });
    </script>
  <% end %>
</div>

app/views/users/posts/new.html.erb
<h2 class="ui center aligned icon header">
  <!-- <i class="circular home icon"></i> -->
  就快完成囉！
</h2>
<%= render 'form' %>

app/views/users/posts/preview.html.erb
<h2 class="ui center aligned header" style="margin-bottom: 30px;">
  <!-- <i class="circular home icon"></i> -->
  預覽您的物件
</h2>

<div id="home">
  <div class="ui grid">
    <div class="row">
      <div class="column no_horizontal_paddings">
        <%= render "posts/post", post: @post %>
      </div>
    </div>
  </div>
</div>

<%= stylesheet_link_tag 'owl-carousel/owl.carousel.css', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'owl-carousel/owl.theme.css', media: 'all', 'data-turbolinks-track' => true %>

<%= content_for :custom_js do %>
  <%= javascript_include_tag 'owl-carousel/owl.carousel.js', 'data-turbolinks-track' => false %>

  <script type="text/javascript">
    $(".owl-carousel").owlCarousel({
      //autoPlay: 3000, //Set AutoPlay to 3 seconds
      //singleItem: true,
      items: 1,
      itemsDesktop: false,
      itemsDesktopSmall: false,
      itemsTablet: false,
      itemsTabletSmall: false,
      lazyLoad : true,
      navigation : false,
      pagination : false,
    });
  </script>
<% end %>

app/views/users/posts/show.html.erb
<%= render 'posts/post', post: @post %>

app/views/users/posts/upload_photo.html.erb
<h2 class="ui center aligned icon header">
  <!-- <i class="circular home icon"></i> -->
  請提供幾張照片
</h2>

<div class="center">
  <h3 id="upload_zone" class="ui icon header">
    <i class="icon bordered huge plus black"></i>
    <div class="content">
      選擇圖片
    </div>
  </h3>
  <!-- The file input field used as target for the file upload widget -->      
</div>

<style type="text/css">
  canvas {
    width: 100%;
  }
</style>
<input class="hidden" id="fileupload" type="file" name="file[]" multiple="">

<div id="files" class="files ui stackable grid container center"></div>

<% form_tag update_attachment_post_path, multipart: true, id: "upload_form" do %>
  <%= file_field_tag "file[]", multiple: true, class: 'hidden' %>
  <%#= semantic_icon('remove deletePhoto') %>
  <div class="center">  
    <!-- <h3 class="ui center aligned segment main-bottom-btn" id="upload_zone">輕按選擇圖片</h3> -->
    <div class="ui stackable four column grid" id="photoPreviewBlock"></div>
    <!-- <button class="ui basic large button hidden submit-buttom" id="upload_button">確定上傳</button> -->
    <%= button_tag "開始上傳", type: "submit", class: "ui button yellow hidden", id: "upload_button" %>
  </div>
<% end %>

<div id="images" class="ui stackable grid container">
  <% if @post.attachments_count.present? && @post.attachments_count > 0 %>
    <% @post.attachments.each do |a| %>
      <div class="four wide column" style="text-align: center;">
        <i class="remove icon huge red" style="position: absolute; margin-left: 0px; right: 0px;" data-id="<%= a.id %>"></i>
        <%= image_tag a.image.medium.url, class: 'center' %>
        <!-- <div class="desc"><%#= text_area_tag 'description', a.description %></div> -->
      </div>
    <% end %>
  <% end %>
</div>
<div class="center">
  <%= link_to preview_post_path(@post), class: "ui green button submit-buttom hidden" do %>
    下一步
  <% end %>
</div>

<%= content_for :custom_js do %>
  <%= javascript_include_tag 'jQueryFileUpload/load-image.all.min', 'data-turbolinks-track' => true %>
  <script src="//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'jQueryFileUpload/jquery.iframe-transport', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jQueryFileUpload/jquery.fileupload', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jQueryFileUpload/jquery.fileupload-process', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jQueryFileUpload/jquery.fileupload-image', 'data-turbolinks-track' => true %>
  <script type="text/javascript">
    $('#upload_zone').click(function(){
      $('#fileupload').click()
    })
  </script>
  <script type="text/javascript">
    
    $(function () {
      $('.submit-buttom').toggleClass('hidden', $('#images .icon.remove').length === 0)
      $('#fileupload').fileupload({
        url: "<%= update_attachment_post_path %>",
        dataType: 'json',
        start: function (e) {
          $("#upload_zone").find('i.icon').replaceWith('<i class="spinner loading huge icon"></i>');
          $("#upload_zone").find('.content').html("上傳中，請稍候...")
          $("#upload_zone").unbind( "click" );
        },
        done: function (e, data) {
          // console.log(data.result.file.url)
          $("#upload_zone").find('i.icon').removeClass('loading')
          $('#images').prepend('<div class="four wide column" style="text-align: center;"><i class="remove icon huge red" style="position: absolute; margin-left: 0px; right: 0px;"></i><img src="' + data.result.file.thumbnailUrl + '" class="center"/></div>')
          if ($('#images .icon.remove').length > 0) {
            $('.submit-buttom').removeClass('hidden')
          };
          $("#upload_zone").find('i.icon').replaceWith('<i class="icon bordered huge plus black"></i>');
          $("#upload_zone").find('.content').html("繼續選擇圖片")
          $('#upload_zone').click(function(){
            $('#fileupload').click()
          })
        }
      })

      $('#images .icon.remove').click(function(){
        $(this).parent("div.column").remove();
        if ($('#images .icon.remove').length === 0) {
          $('.submit-buttom').addClass('hidden')
        }
        file_id = $(this).data('id');
        $.ajax({
          type      : 'DELETE',
          data      : { "attachment": { "id": file_id } }, // our data object
          url       : "/attachments/"+file_id, // the url where we want to POST
          dataType  : 'json', // what type of data do we expect back from the server
          encode    : true
        })
        // using the done promise callback
        .done(function(data) {

          // log data to the console so we can see
          console.log(data);

          // here we will handle errors and validation messages
        });
      })
    });

  </script>
<% end %>