config/routes.rb
Rails.application.routes.draw do

  root "pages#posts"
  
  get "search" => "pages#search"
  get "manage" => "pages#manage"
  get "profile" => "pages#profile"

  resources :attachments, only: [:destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope module: "users" do
    resources :posts do
      collection do
        get "remind_for_draft"
      end
      member do
        get "upload_photo"
        post "update_attachment"
        get "preview"
        post "publish"
        post "unpublish"
      end
    end
  end

end

app/views/pages/manage.html.erb
<div class="sixteen wide mobile eight wide tablet eight wide computer column">
  <a id="new_post_button" class="ui button" href="<%= new_post_path %>">
    <i class="icon add"></i>
    Post in 1 minute.
  </a>
</div>
<div class="ui grid">
  <% @posts.publish.each do |post| %>
    <div class="row">
      <div class="column no_horizontal_paddings">
        <%= render post %>
      </div>
    </div>
  <% end %>
</div>
<h2 class="ui center aligned icon header">
  <!-- <i class="circular home icon"></i> -->
  It's almost done.
</h2>
<%= render 'posts/form' %>

app/views/pages/posts.html.erb
<div id="home">
  <div class="ui grid">
    <% if params[:q] && params[:q][:city_or_description_or_address_cont_any].present? && params[:q][:city_or_description_or_address_cont_any].is_a?(Array) %>
      <div class="row">
        <span class="center">為您找到 <%= @posts.size %> 間與<%= params[:q][:city_or_description_or_address_cont_any].map{|s| "「"+s+"」"}.join(" 或 ") %>相關的房源</span>
      </div>
    <% end %>
    <% @posts.publish.each do |post| %>
      <div class="row">
        <div class="column no_horizontal_paddings">
          <%= render post %>
        </div>
      </div>
    <% end %>
  </div>

  <%= stylesheet_link_tag 'owl-carousel/owl.carousel.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'owl-carousel/owl.theme.css', media: 'all', 'data-turbolinks-track' => true %>

  <%= content_for :custom_js do %>
    <%= javascript_include_tag 'owl-carousel/owl.carousel.js', 'data-turbolinks-track' => true %>
    <script type="text/javascript">
      $(document).ready(function() {
        $(".owl-carousel").owlCarousel({
            //autoPlay: 3000, //Set AutoPlay to 3 seconds
            //singleItem: true,
            items: 1,
            itemsDesktop: false,
            itemsDesktopSmall: false,
            itemsTablet: false,
            itemsTabletSmall: false,
            lazyLoad : true,
            navigation : false,
            pagination : false,
        });
      });
    </script>
  <% end %>
</div>

<%= content_for :footer do %>
  <%= render_main_btn("刊登房屋", remind_for_draft_posts_path, class:"hidden") %>
<% end %>

<% content_for :custom_js do %>
  <script type="text/javascript">
    $(window).load(function(){
      var totalHTMLHeight = $(document).height()
      var currentBottomY = $(window).scrollTop() + $(window).height()
      $(document).scroll(function(){
        totalHTMLHeight = $(document).height()
        currentBottomY = $(window).scrollTop() + $(window).height()
        $('.main-bottom-btn').toggleClass('hidden', currentBottomY <= totalHTMLHeight-100)  
      });
    });
  </script>
<% end %>

app/views/pages/profile.html.erb
<div class="center" id="profile">
  <%= image_tag current_user.image, class: 'ui circular center image', id: 'user-avatar' %>
  <h2 class="ui center aligned header" style="margin: 15px; font-weight: normal;">
    <%= current_user.name %>
  </h2>

  <div class="ui fluid one item labeled icon menu" id="post-btn">
    <%= link_to new_post_path, class:'item' do %>
      <i class="plus icon"></i>
      刊登房屋
    <% end %>
  </div>

  <div class="ui fluid three item labeled icon menu" id="profile-actions">
    <%= link_to posts_path, class:'item' do %>
      <i class="home icon"></i>
      管理房屋
    <% end %>
    <%= link_to ENV["zuker_community_shorturl"], class:'item', target:"_blank" do %>
      <i class="facebook square icon"></i>
      關於 Zuker
    <% end %>
    <%= link_to destroy_user_session_path, :method => :delete, class:'item' do %>
      <i class="sign out icon"></i>
      登出
    <% end %>
  </div>

</div>

<%= content_for :footer do %>
  <%#= render_main_btn("刊登房屋", remind_for_draft_posts_path) %>
<% end %>

app/views/pages/search.html.erb
<%= search_form_for @q do |f| %>
  <div class="ui stackable grid center action_wrapper" id="action_wrapper">
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui action fluid input">
        <% if browser.platform.ios? %>
          <div class="ios_dropdown_with_icon">
            <%= f.collection_select :city_eq, I18n.t('cities'), :last, :last, {include_blank: "城市"}, class: "ui selection compact dropdown default" %>
            <i class="dropdown icon"></i>
          </div>
        <% else %>
          <%= f.collection_select :city_eq, I18n.t('cities'), :last, :last, {include_blank: "城市"}, class: "ui fluid search selection dropdown" %>  
        <% end %>
      </div>
    </div>
    <div class="sixteen wide mobile eight wide tablet eight wide computer column">
      <div class="ui fluid input" id="search_input">
        <%= f.search_field :city_or_description_or_address_cont_any, placeholder: "搜尋地址、敘述..." %>
      </div>
    </div>
  </div>
  <div class="column center fixed-button-wrapper">
    <%= f.submit "Continue", class: "ui button yellow submit-buttom fixed-button" %>
  </div>
<% end %>