config/routes.rb
Rails.application.routes.draw do

  root "pages#posts"
  
  get "search" => "pages#search"
  get "manage" => "pages#manage"
  get "profile" => "pages#profile"

  resources :attachments, only: [:destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope module: "users" do
    resources :posts do
      collection do
        get "remind_for_draft"
      end
      member do
        get "upload_photo"
        post "update_attachment"
        get "preview"
        post "publish"
        post "unpublish"
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>極速刊登 - Zuker</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '<%= ENV["google_analytics_key"] %>', 'auto');
    ga('send', 'pageview');
  </script>
</head>
<body class="snow">
  

  <div class="ui left vertical inverted sidebar labeled icon menu">
    <a class="item<%= ' active' if action_name == 'posts' %>" href="/">
      <i class="big home icon"></i>
      首頁
    </a>
    <a class="item <%= render_active(action_name == 'profile' || current_page?(controller:'devise/sessions', action:'new')) %>" href="<%= user_signed_in? ? profile_path : new_user_session_path %>">
      <i class="big user icon"></i>
      帳號管理
    </a>
  </div>

  <div class="pusher">
    <div class="ui top attached menu">
      <a class="item" style="position: absolute; height: 52.1406px;">
        <i class="sidebar icon"></i>
      </a>
      <%= link_to root_path, class: "logo item center", id: "logo-img-link" do %>
        <%= image_tag 'https://s3.amazonaws.com/superpostimages/uploads/default/logo-f.png', id: "logo-img" %>
      <% end %>
    </div>

    <% if flash.any? %>
      <% flash.map do |type, message| %>
        <div class="ui icon message <%= type.to_s == 'success' ? 'success' : 'info' %>">
          <i class="<%= type.to_s == 'success' ? 'checkmark' : 'info' %> icon"></i>
          <div class="header">
            <%= raw message %>
          </div>
        </div>
      <% end %>
    <% end %>

    <%= yield :outside %>
    <div class="ui main container <%= 'large-margin-bottom' if (current_page?(root_path) || action_name == 'upload_photo') %>">
      <%= yield %>
    </div>

    <%= render "partials/footer" %>
  </div>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :custom_js %>
  <script type="text/javascript">
    $('i.sidebar.icon').parent('a.item').click(function(){
      $('.ui.sidebar')
        .sidebar('toggle')
      ;
    })
  </script>
</body>
</html>